ContactoDB/Models/ContactoModel.cs
using System.ComponentModel.DataAnnotations;
namespace ContactoDB.Models
{
    public class ContactoModel
    {
        public int IdContacto { get; set; }


        [Required(ErrorMessage="El campo Nombre es obligatorio")]
        public string Nombre { get; set; }


        [Required(ErrorMessage="El campo Telefono es obligatorio")]
        public string Telefono { get; set; }
        
        public string? Correo { get; set; } //Opcional


        [Required(ErrorMessage = "El campo Clave es obligatorio")]
        public string Clave { get; set; }
    }
}

ContactoDB/Models/ErrorViewModel.cs
namespace ContactoDB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ContactoDB/Controllers/ContactoController.cs
using Microsoft.AspNetCore.Mvc;
using ContactoDB.Datos;
using ContactoDB.Models;
using System.Security.Permissions;

namespace ContactoDB.Controllers
{
    public class ContactoController : Controller
    {
        ContactoDatos contactoDatos = new ContactoDatos();
        public IActionResult Listar()
        {
            var lista = contactoDatos.ListarContacto();
            return View(lista);
        }
        [HttpGet] //Para que acrgue el formulario
        public IActionResult Guardar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Guardar(ContactoModel model)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            var respuesta = contactoDatos.GuardarContacto(model);
            if (respuesta) 
                return RedirectToAction("Listar"); //vista a la que queremos reenviar
            else
            {
                return View();
            }

        }
        [HttpGet]
        public IActionResult Editar(int IdContacto)
        {
            ContactoModel contacto = contactoDatos.ObtenerContacto(IdContacto);
            return View(contacto);
        }
        [HttpPost]
        public IActionResult Editar(ContactoModel model)
        {
            var resultado = contactoDatos.EditarContacto(model);
            if(resultado)
            {
                return RedirectToAction("Listar");
            }
            else
            {
                return View();
            }
        }
        [HttpGet]
		public IActionResult Eliminar(int id)
		{
			var contacto = contactoDatos.ObtenerContacto(id);
            return View(contacto);
		}
        [HttpPost]
        public IActionResult Eliminar(ContactoModel model)
        {
            var respuesta = contactoDatos.EliminarContacto(model);
            if(respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
            {
                return View();
            }

        }
	}
}

ContactoDB/Controllers/HomeController.cs
using ContactoDB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ContactoDB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ContactoDB/Views/Contacto/Editar.cshtml
@model ContactoDB.Models.ContactoModel;
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card col-8">
    <div class="card-header">
		<h1>Editar</h1>
    </div>
    <div class="card-body">
        @*FORMULARIO PARA EDITAR*@
        <form asp-action="Editar" asp-controller="Contacto" method="post">
            <input type="hidden" asp-for="IdContacto" class="form-control"/>
            <div class="col-md-4 mb-3">
                <label for="Nombre"> Nombre </label>
                <input type="text" class="form-control" asp-for="Nombre" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="col-md-4 mb-3">
                <label for="Telefono"> Teléfono </label>
                <input type="text" class="form-control" asp-for="Telefono" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="col-md-4 mb-3">
                <label for="Correo"> Correo </label>
                <input type="text" class="form-control" asp-for="Correo" />
            </div>
            <div class="col-md-4 mb-3">
                <label for="Clave"> Clave </label>
                <input type="text" class="form-control" asp-for="Clave" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>
            <div class="col-md-4 mb-3">
                <button type="submit" class="btn btn-primary mb-3">
                    Guardar
                </button>
                <a asp-controller="Contacto" asp-action="Listar">Volver a la lista</a>
            </div>
        </form>
    </div>
</div>

ContactoDB/Views/Contacto/Eliminar.cshtml
@model ContactoDB.Models.ContactoModel;
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card col-8">
    <div class="card-header">
		<h1>Eliminar</h1>
    </div>
    <div class="card-body">
        <form asp-action="Eliminar" asp-controller="Contacto" method="post">
            <input type="hidden" asp-for="IdContacto" class="form-control"/>
            <div class="alert alert-danger" role="alert"> 
                ¿Deseas eliminar contacto: @Html.DisplayTextFor(m=>m.Nombre)?
            </div>
            <div class="col-md-4 mb-3">
                <button type="submit" class="btn btn-danger mb-3 btn-sm"> Eliminar </button>
                <a asp-action="Listar" asp-controller="Contacto" class="btn btn-warning btn-sm"> Volver a la lista</a>
            </div>
        </form>
    </div>

</div>

ContactoDB/Views/Contacto/Guardar.cshtml
@model ContactoDB.Models.ContactoModel;
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Guardar</h1>
<div class="card" style="width: 18rem;">
    <div class="card-header">
        Crear Contacto
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Contacto" method="post"> @*FORMULARIO*@
            <div class="col-md-4 mb-3">
                <label for="Nombre"> Nombre </label>
                <input type="text" class="form-control" asp-for="Nombre"/>
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="col-md-4 mb-3">
                <label for="Telefono"> Teléfono </label>
                <input type="text" class="form-control" asp-for="Telefono"/>
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="col-md-4 mb-3">
                <label for="Correo"> Correo </label>
                <input type="text" class="form-control" asp-for="Correo"/>
            </div>
            <div class="col-md-4 mb-3">
                <label for="Clave" > Clave </label>
                <input type="text" class="form-control" asp-for="Clave"/>
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>
            <div class="col-md-4 mb-3">
                <button type="submit" class="btn btn-primary mb-3">
                    Guardar
                </button>
                <a asp-controller="Contacto" asp-action="Listar">Volver a la lista</a>
            </div>
        </form>
    </div>
</div>

ContactoDB/Views/Contacto/Listar.cshtml
@model List<ContactoModel>;
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card col-8">
    <div class="card-header">
        <h1>Listar Contactos</h1>
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Contacto" class="btn btn-success"><i class="bi bi-file-earmark-plus"> </i> Crea Nuevo Contacto </a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                    <th>Clave</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Telefono</td>
                        <td>@item.Correo</td>
                        <td>@item.Clave</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Contacto" asp-route-idContacto="@item.IdContacto" class="btn btn-warning btn-sm"><i class="bi bi-pencil"> </i>Editar</a>
                            <a asp-action="Eliminar" asp-controller="Contacto" asp-route-idContacto="@item.IdContacto" class="btn btn-danger btn-sm"><i class="bi bi-trash"> </i>Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ContactoDB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ContactoDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContactoDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContactoDB.styles.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ContactoDB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Guardar">Contacto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ContactoDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>